[build]
  command = "cd frontend && yarn install --frozen-lockfile && yarn build"
  publish = "frontend/build"

[build.environment]
  YARN_PRODUCTION = "false"
  NODE_ENV = "development"
  NODE_VERSION = "20"
